### ISSUE TITLE
Fail gracefully if -f is not given any files

### ISSUE THREAD

**Issue by SaschaMann** [ErikSchierboom/MarkdownLinkChecker#10]
In case one only wants to run the check against a list of files, e.g. changed files in a PR, it'd be useful to accept no `markdownlinkchecker -f` as success. Or perhaps with an `--allow-empty` flag. There may not be any changed files, so right now one has to add a bash workaround to check if files is empty or it'll fail.

**Comment by ErikSchierboom** [comment]
I've tried to implement this, but the argument parsing library that I use does not support this. I've also checked an alternative library, but it too does not support it :(

**Comment by ErikSchierboom** [comment]
I'm gonna try some different approaches.

**Comment by ErikSchierboom** [comment]
I've been unable to fix this in the library. It would require quite a bit of coding if I were to write this myself. Note that `xargs` has an option to not run a command if no matches were found: https://stackoverflow.com/questions/8296710/how-to-ignore-xargs-commands-if-stdin-input-is-empty/8296746#8296746
